### ISSUE TITLE
User-defined schemes on wine

### ISSUE THREAD

**Issue by plastikat** [colorer/FarColorer#13]
I know this issue is a bit strange (and very unlikely supported) one, but I've decided to report it anyway...

I've got some user-defined schemes (loaded from `base\hrc\auto\` directory) and these worked fine up until (and including) version 1.2.2.4. Unfortunately, they don't work anymore on [wine](https://en.wikipedia.org/wiki/Wine_%28software%29) with version 1.2.2.5 (and later until 1.2.4.0). They just don't get loaded like there's none of them (while the plugin itself is loaded and standard schemes work fine). *But* if I put them on some path and specify it as "Users file of schemes" in settings - they get loaded...

At the same time, on Windows 8.1 x86, the same user schemes are loaded fine from `base\hrc\auto\` with versions 1.2.2.5+, thus the issue seems to be wine-specific.

The issue has most likely been introduced by changes in `FarHrcSettings::UpdatePrototype` in commit efa79467ac91fbdc13401fc2c4681a701e96f8cf, as it seems the only relevant change.

My environment:
wine 1.6.2 (1:1.6.2-0ubuntu4) @ Ubuntu 14.04
Far 3.0.4541 x86 started as:
`wineconsole C:\Programs\Far\Far.exe`

**Comment by ctapmex** [comment]
strange. there is, in addition to this commit, colorer library has been updated. and it was a struggle with memory leaks in destructors. but I do not see any problems there.
offer to do so - in the coming days, I completed yet logging in the plugin, and the new assembly will try to debug.

**Comment by plastikat** [comment]
When I had been trying to investigate the problem in the first place I've tried different combinations of the plugin and colorer library versions (replacing separately the whole `base` or `bin` directories). Colorer library doesn't seem to affect this issue, only plugin files do.

**Comment by ctapmex** [comment]
received confirmation that the problem is on the windows. I will check

**Comment by ctapmex** [comment]
find error: this is visual c++ 2015 bug http://stackoverflow.com/questions/32452777/visual-c-2015-express-stat-not-working-on-windows-xp
