### ISSUE TITLE
функции определения текущего состояния, включения, выключения (FarColorer-Configure-Enabled)

### ISSUE THREAD

**Issue by z0hm** [colorer/FarColorer#18]
Предлагаю добавить вышеназванные функции и сделать их доступными из luascript макросов, например через Plugin.Call().

**Comment by ctapmex** [comment]
т.е. только вкл/выкл?

**Comment by z0hm** [comment]
Помимо On/Off, хотелось бы и чтение текущего состояния - включен или выключен, чтобы можно было из скрипта его запомнить, а после неких действий восстановить, т.е. save/restore.

**Comment by VictorVG** [comment]
**ctapmex**
**z0hm**

Операция save/restore по отношению к плагину штука внешняя. Достаточно реализации _Plugin.Config()_ с возможностью чтения/установки настроек по двум разделам: общие которые сгруппированы в меню _Настройки FarColorer_ (GUID "87C92249-430D-4334-AC33-05E7423286E9") и схем которые сгруппированы в подменю _Настройка параметров схем_  (GUID "0497F43A-A8B9-4AF1-A3A4-FA568F455707"), и опционально (?), для чего наверное (я в этом не уверен) стоит добавить отдельный GUID для пункта _Тест библиотеки схем_ чтобы его было возможно вызвать через механизм _Plugin.Menu()_ для перезапуска текущей схемы (иногда это требуется, хотя и редко, потому необходимости в отдельной операции _Перезагрузить схемы_ я не вижу).

А операции сохранения/восстановления/резервирования/изменения настроек это уже забота внешних макросов. 

**ctapmex**

Единственное что мне лично более нравится, но это мои личные предпочтения, это использование _Plugin.Menu()_ вместо _Plugin.Call()_ , и если бы была такая возможность, добавить в _./src/pcolorer.h_  GUID-ы для вызова команд плагина через _Plugin.Menu()_ я лично был бы очень доволен. Но, ещё раз оговорюсь, что это личное пожелание из серии "_лично мне это было бы удобно_" о котором стоит говорить только если против него нет возражений и если оно никому и ничему мешать не будет. Если оно есть хоть какое препятствие оно отбрасывается без вопросов.

**Comment by shmuz** [comment]
Виктор, Plugin.Menu работает **только** для пункта/пунктов фаровского меню плагинов, которое вызывается по F11. Поэтому оно не является полноценной заменой Plugin.Call.

**Comment by VictorVG** [comment]
Н-н-да, тоды ой. Вопрос снимаю.

**Comment by ctapmex** [comment]
как принято вести себя в макросах, если при выполнении команды возникает ошибка/исключение? просто вернуть  false? а если выводится ошибка на экран - её гасить ?

**Comment by shmuz** [comment]
> как принято вести себя в макросах, если при выполнении команды возникает ошибка/исключение? просто вернуть false? а если выводится ошибка на экран - её гасить ?

Если я правильно понял, вопрос не о макросах вообще, а о поведении плагина, вызванного из макроса. В этом случае плагин сам решает, как ему поступать. Может вывести сообщение об ошибке, а может не выводить и просто вернуть NULL. (Если вопрос был неправильно понят - уточните).

**Comment by ctapmex** [comment]
да, вопрос правильно понят.
в текущей реализации плагина все ошибки отображаются на экран. наиболее частое это попытка включения плагина. вот и думаю, либо делать отдельную логику для вызова из макроса, или использовать тот же код что есть

**Comment by shmuz** [comment]
Попробуйте для начала использовать существующие механизмы, а если возникнет проблема, тогда будет о чём говорить более конкретно.

**Comment by shmuz** [comment]
Для информации:
если плагин из макроса вызван "асинхронно" (то есть посредством `Plugin.Call`), то при выводе плагином любого диалога или меню на экран макрос немедленно получит управление назад, с величиной возврата `true`. Но это уже проблема макрописателя, а не плагина.

**Comment by ctapmex** [comment]
реализовал, в очередной сборке проверяйте

**Comment by z0hm** [comment]
Имхо нелогично - статус возвращаем бинарной переменной, а устанавливаем строковой, соответственно, для восстановления состояния вместо передачи переменной status, требуется выражение: 
`status and "enable" or "disable"`
  
 Имхо лучше: без 2-го аргумента, либо он =nil - возвращаем статус true/false, устанавливаем статус передачей true/false 2-ым аргументом. Возможно есть смысл и в возврате статуса установки статуса: true - статус изменён, false - статус изменить не удалось.

**Comment by ctapmex** [comment]
согласен, не логично. но что ты имеешь ввиду под 2-ым аргументом?
в документации примеров нет, а из описания получаем что в функции call всего два аргумента: guid и  еще один. 
N=plugin.call(Guid[,param])
если его делать как 0/1 для установки статуса, то как быть если я захочу еще что-то добавить? делать 3...100 ? тоже так себе.
вот если бы была поддержка 
N=plugin.call(Guid,param1,param2...) то было бы замечательо

**Comment by shmuz** [comment]
> из описания получаем что в функции call всего два аргумента: guid и еще один.
N=plugin.call(Guid[,param])

Это не так. И аргументов, и возвращаемых значений может быть практически сколько угодно.
Описание макросов в Энциклопедии Far во многих местах устарело.
1. Смотрите описание функции `OpenW` (и пройдите по ссылкам).
2. Для макрописателя имеет смысл читать _macroapi_manual.ru.chm_ (статья о `Plugin.Call`).

**Comment by ctapmex** [comment]
ок, вижу по пункту 2.
предлагаю согласовать желаемый синтаксис, чтобы не переделывать потом.
plugin.call(Guid, "status") - текущий статус
plugin.call(Guid, "status", new_status) - установка нового статуса

**Comment by VictorVG** [comment]
@ctapmex 

**Fix typo** - попались на глаза в ./FarColorer/misc/colorer?.hlf опечатки в блоке `@MacroCallPlugin` - _disbale_ вместо _disable_ . Пофиксил, можно смержить - [**FarColorer_doc_fixed.zip**](https://github.com/colorer/FarColorer/files/785964/FarColorer_doc_fixed.zip) пока не забыли...

по пункту 2) мне это кажется удобным, т.к. Plugin.Call() может передать массив параметров с разделителями, а там пусть плагин свою комстроку сам парсит.

**Comment by VictorVG** [comment]
Кстати, вот что вылезает - если плагин отключён, то хотя Plugin.Call и возвращает 0 в тесте lua:Colorer_test.lua  ([**Colorer_test.lua.zip**](https://github.com/colorer/FarColorer/files/786009/Colorer_test.lua.zip))

 это не видно:
```
Plugin.Call("D2F36B62-A470-418D-83A3-ED7A3710E5B5","enable") mf.msgbox("FarColorer status",Plugin.Call("D2F36B62-A470-418D-83A3-ED7A3710E5B5","status"));
Plugin.Call("D2F36B62-A470-418D-83A3-ED7A3710E5B5","disable") mf.msgbox("FarColorer status",Plugin.Call("D2F36B62-A470-418D-83A3-ED7A3710E5B5","status"));
```

Первая строка скрипта выведет:

![1](https://cloud.githubusercontent.com/assets/906886/23104463/7167769c-f6df-11e6-9204-d3fbacda01ff.png)

вторая:

![2](https://cloud.githubusercontent.com/assets/906886/23104465/795e2238-f6df-11e6-8583-b73997abdc31.png)

**Comment by ctapmex** [comment]
я все согласно документации делал. возвращаю либо 0, либо INVALID_HANDLE_VALUE

>  - Если плагин не найден или вернул 0, макросу возвращается false.
>  - Если плагин вернул 1 или INVALID_HANDLE_VALUE, макросу возвращается true.

**Comment by shmuz** [comment]
@VictorVG, если хотите посмотреть, что возвращается, используйте `far.Show`, а не `msgbox`.

**Comment by VictorVG** [comment]
@shmuz 

уже в своих тестах нашёл ошибку - не тот гуид использовал. главное новый механизм работает.

**Comment by z0hm** [comment]
К этому пришли?
```
local ColorerStatus=Plugin.Call(GUID,"status")
Plugin.Call(GUID,"status",ColorerStatus)
```
?

**Comment by VictorVG** [comment]
Почти:

> Версия 1.2.9.1 . 19.02.2017
> 	1. уточнение plugin.call:
> 	    - Plugin.Call("0E92FC81-4888-4297-A85D-31C79E0E0CEE","status"). Возвращаемое значение: true - плагин включен, false - выключен
> 	    - Plugin.Call("0E92FC81-4888-4297-A85D-31C79E0E0CEE","status", new_status). Перевод плагина в статус new_status.
>             new_status - true/false, либо соответсвующее им целое значение.
>             Возвращаемое значение true/false показывает успешность выполнения команды.
тесты:
```
far.Message("Begin FarColorer status test");
local CLRS = Plugin.Call(CLRG,"status");

local CLRG = "0E92FC81-4888-4297-A85D-31C79E0E0CEE";
far.Message("Status before all tests")
  Plugin.Call(CLRG,"status");
  far.Show(status)

far.Message("Test command Enable");
  Plugin.Call(CLRG,"enable")
   Plugin.Call(CLRG,"status");
   far.Show(status)

far.Message("Test command Disable");
  Plugin.Call(CLRG,"disable")
   Plugin.Call(CLRG,"status");
   far.Show(status)

far.Message("Test restore settings");
  Plugin.Call(CLRG,"status",CLRS)
   Plugin.Call(CLRG,"status");
   far.Show(status)

far.Message("Status after all tests");
   Plugin.Call(CLRG,"status");
   far.Show(status)
```
а последний вариант теста у меня такой:
```
far.Message("Begin FarColorer status test");
local CLRS,STS;
local CLRG = "0E92FC81-4888-4297-A85D-31C79E0E0CEE";
      CLRS = Plugin.Call(CLRG,"status");

far.Message("FarColorer status before all test");
    STS=Plugin.Call(CLRG,"status");
      if STS == true then far.Message("Enabled") else far.Message("Disabled") end;

far.Message("Test command Enable");
  Plugin.Call(CLRG,"enable")
      STS=Plugin.Call(CLRG,"status");
      if STS == true then far.Message("Enabled") else far.Message("Disabled") end;

far.Message("Test command Disable");
  Plugin.Call(CLRG,"disable")
       STS=Plugin.Call(CLRG,"status");
      if STS == true then far.Message("Enabled") else far.Message("Disabled") end;

far.Message("Test restore settings");
  Plugin.Call(CLRG,"status",CLRS);
      STS=Plugin.Call(CLRG,"status");
      if STS == true then far.Message("Enabled") else far.Message("Disabled") end;
```
и он всё время по far.Show() выводит nil .... Явно я что-то не правильно делаю

**Comment by VictorVG** [comment]
Колорер я выложил у себя, но ещё и нетбокс обновился, так что я и его сейчас соберу, а обновлю сразу оптом. :)

**Comment by z0hm** [comment]
Не работает так как надо.
test.lua
```
local Colorer="0E92FC81-4888-4297-A85D-31C79E0E0CEE"

Macro {
area="Shell"; key="ColorerStatus"; flags=""; description="* ColorerStatus *"; 
action=function()
  local fd=Far.DisableHistory(-1)
  -- mmode(1,0)
  local ColorerStatus=Plugin.SyncCall(Colorer,"status")
  Plugin.SyncCall(Colorer,"status",false)
  far.Show("off",Plugin.SyncCall(Colorer,"status"))
  local a0="0.txt"
  local a1="1.txt"
  if mf.fexist(a1) then Panel.SetPos(0,a1) Keys('ShiftDel Enter') end
  if mf.fexist(a0) then
    Panel.SetPos(0,a0) Keys('F5') print(a1) Keys('Enter')
    Panel.SetPos(0,a1) Keys('F4 CtrlHome')
    far.Show("a1",Plugin.SyncCall(Colorer,"status"))
    Keys('F2 Esc')
  end
  Plugin.Call(Colorer,"status",ColorerStatus)
  Far.DisableHistory(fd)
end
}
```
Создаём в тестовой папке 0.txt с цветным содержимым, например 'A 0' (буква голубая, цифра зелёная). Вызываем из панелей test.lua: lua:eval("ColorerStatus",2) - оба раза видим false (colorer off), но текст цветной.

**Comment by VictorVG** [comment]
Факт

**Comment by shmuz** [comment]
Мои проверки показывают, что плагин нормально отрабатывает все 3 варианта вызова.

**Comment by shmuz** [comment]
@z0hm, в вашем `test.lua` GUID плагина Colorer неправильный. Поэтому, видимо, и не работает.

**Comment by z0hm** [comment]
Точно,Витина диверсия )

**Comment by VictorVG** [comment]
Смех в том, что GUID тут взял [**docs/history.ru.txt**](https://raw.githubusercontent.com/colorer/FarColorer/ad550c5c43a057a677c3065672f9ed4e8c5ddeaa/docs/history.ru.txt ) :+1: 

> Версия 1.2.9.1 . 19.02.2017
> 	1. уточнение plugin.call:
> 	    - Plugin.Call("0E92FC81-4888-4297-A85D-31C79E0E0CEE","status"). Возвращаемое значение: true - плагин включен, false - выключен
> 	    - Plugin.Call("0E92FC81-4888-4297-A85D-31C79E0E0CEE","status", new_status). Перевод плагина в статус new_status.
>             new_status - true/false, либо соответсвующее им целое значение.
>             Возвращаемое значение true/false показывает успешность выполнения команды.
> 
> Версия 1.2.9.0 . 19.02.2017
> 	1. ошибка вызова plugin.call при не инициализированном плагине
> 	2. новые команды для plugin.call:
> 	    - Plugin.Call("0E92FC81-4888-4297-A85D-31C79E0E0CEE","status")  true - плагин включен, false - выключен
> 	    - Plugin.Call("0E92FC81-4888-4297-A85D-31C79E0E0CEE","enable")  включение плагина
> 	    - Plugin.Call("0E92FC81-4888-4297-A85D-31C79E0E0CEE","disable")  выключение плагина

ладно, посмотрю в исходниках - может в доке опечатка?

**Comment by shmuz** [comment]
Зачем ковыряться в исходниках, когда можно нажать в редакторе F11, стать на пункт плагина и нажать F3.

**Comment by VictorVG** [comment]
Так и решил поступить. Ставлю GUID плагина - тест 1 всюду выводит _nil_ , тест 2 у меня всюду говорит Enabled, а плагин работает. Так что походу в тесте всё же напутал....

**Comment by VictorVG** [comment]
Футы нуты!, факт напутал, только в ином месте  - _я ждал в тесте ответта о статусе плагина а проверял успешность выполнения команды_

**Comment by ctapmex** [comment]
мда, не хорошо получилось. но главное что работает

**Comment by VictorVG** [comment]
У себя я доки поправлю, закинуть правки? А то ещё кто на опечатку нарвётся?

**Comment by VictorVG** [comment]
Готово: [**docs_patch.zip**](https://github.com/colorer/FarColorer/files/788190/docs_patch.zip) - я исправил неверный GUID и указал правильный формат вызова Plugin.Call(GUID[,parms]) вместо невенрного названия функции callplugin().

**Comment by VictorVG** [comment]
Подправил ... недоправленные мелочи.:)

**Comment by z0hm** [comment]
Имхо есть смысл в допкоманде - установке статуса с возвратом предыдущего статуса, либо 2-х статусов - выполнения и предыдущего состояния? - Тогда бы вместо 2-х Plugin.Call(), можно было бы использовать 1.

**Comment by VictorVG** [comment]
А смысл в вызове _"status",res_? Его всё одно надо где-то запоминать и если между первым изменением и восстановлением статуса происходят какие либо изменяющие его  операции , то результат восстановления становится не предсказуем.

Тогда есть смысл добавления не одной, а двух новых команд  - _save_ и _load_ , где:

_save_ - в зависимости от контекста вызова панели/редактор сохраняет текущее значение статуса в БД, различия - если вызвана из панелей то сохраняется глобальное состояние статуса,, если вызвана из редактора то сохраняется состояние только для конкретного Editor ID.

_load_ - восстанавливапет последнее сохранённое в БД состояние статуса, контекстно-зависимое поведение аналогично команде _save_ .

**Comment by z0hm** [comment]
смысла в вызове `"status",res` точно нет, в отличие от: `"status",st` - ведь `res` это статус выполнения, а `st` предыдущее состояние плага до его изменения. Соответственно остаётся только восстановить `st` после извращений.

**Comment by VictorVG** [comment]
Так в любом случае любая операция чтения/записи/модификации состояния на предшествующий данному _status(t)_ моменту времени _status(t-1)_ требует чтобы какой-то механизм сохранил эти данные, и если читать дословно [**предложение**](https://github.com/colorer/FarColorer/issues/18#issuecomment-281483565) то оказывается что используется глобальный механизм сохранения состояния срабатывающий при любой его модификации без учёта контекста выполнения что гарантировано приведёт к ошибкам восстановления состояния, даже в пределах контекста одной задачи.  

В отличии от [**предложения**](https://github.com/colorer/FarColorer/issues/18#issuecomment-281483565) вариант с командами _load/save_ предложенный [**21.02.2017**](https://github.com/colorer/FarColorer/issues/18#issuecomment-281329807) гарантирует что в момент выполнения операций сохранения/восстановления состояния мы будем работать с нужной записью и не получим неопределённых последствий от её востановления.

**Comment by ctapmex** [comment]
что-то вы далеко в дебри пошли. статус плагина един для всего окружения фара. меняется он глобально.
для того чтобы упростить себе скрипты на одну/две строчки вы наоборот городите громадные вызовы с кучей параметров. не проще ли еще строку написать?

вообще, в данном случае мне всё равно. если вы сформулируете устраивающее всех решение. я его сделаю.

**Comment by VictorVG** [comment]
Я думаю что может имеет смысл сделать возможность независимого управления статусом плагина для разных сессий редактора.  Плюсы и минусы такого решения:

Плюсы: 

1) установка статуса в одной сессии редактора не влияет на остальные;
2) возможность сохранения/восстановления произвольного состояния сессии редактора в любой момент времени если оно есть в БД истории;

Минусы:

1) Усложнение алгоритма управления плагином;
2) Макросы как раз усложнятся :) ,  так как мы будем использовать  конструкцию типа Plugin.Call(ColorerGUID,"status",["save"|"load",var]), хотя получат большую гибкость.

В общем и хочется, и колется и в чём-то спорно "А не слишком ли сложно?"....

**Comment by z0hm** [comment]
**ctapmex**
Если возможно: дополнить текущую команду установки статуса также и возвратом предыдущего состояния:  `res,prev_status = Plugin.SyncCall(ColorerGuid,"status",new_status)`
Виктора не слушать - такие огороды не нужны.

**Comment by VictorVG** [comment]
И получаем мину на неизвлекаемость - пример банальный. Отрываем на редактирование скрипт, желаетельно позаковыристей типа такого:

```
#!/bin/sh
# PROVIDE: iso-prepare
# REQUIRE: system-patch
. ../config
. lib/lib.sh

if [ "$1" = "iso" -o "$1" = "all" ]; then
stage_init
stage_check

MTREE="iso/cd.mtree"
FLIST="iso/cd.filelist"
ISODIR="isoroot"
ISOROOT="iso/${ISODIR}"

#[ ! -d "${FRENZY_CD}" ] || chflags -R noschg ${FRENZY_CD} && rm -rf ${FRENZY_CD}
[ -d "${FRENZY_CD}" ]  || err 1 "No such CD dir"

#mkdir ${FRENZY_CD}
# creating directory structure
mtree -eU -f ${MTREE} -p ${FRENZY_CD} > /dev/null 2>&1
# copying boot files
for i in `cat ${FLIST}`
    do
	if [ -f "${FRENZY_FS}/${i}" ]; then
	    cp ${FRENZY_FS}/${i} ${FRENZY_CD}/${i}
#	else
#	    echo "ISO-PREPARE WARNING: No such ${i} file in ${FRENZY_FS}"
	fi

#Override from Frenzy templates
[ ! -f "${ISOROOT}/${i}" ] || cp ${ISOROOT}/${i} ${FRENZY_CD}/${i}

done

# Copy Frenzy patches for ISO
cp -R ${ISOROOT} ${TMPDIR}
find ${TMPDIR}/${ISODIR} -type d -name .svn -exec rm -rf {} \; >> /dev/null 2>&1
rsync -avzd ${TMPDIR}/${ISODIR}/* ${FRENZY_CD}
# Copy boot loader
[ -f "${TMPDIR}/frenzyroot.gz" ] || err 1 "No such ${TMPDIR}/frenzyroot.gz from bootloader stage"
cp ${TMPDIR}/frenzyroot.gz ${FRENZY_CD}/boot


# gzipping kernel
gzip -9 -f ${FRENZY_CD}/boot/kernel/kernel
gzip -9 -f ${FRENZY_CD}/boot/kernel/*.ko

printf "$VERSION" > ${FRENZY_FS}/boot/frenzy.version
echo "[*] File structure for Frenzy ISO created."

fi

stage_done
```
или посложнее, и по ходу дела нам надо другой скрипт глянуть, ну к примеру  такой:

```
#!/bin/sh
# PROVIDE: FRENZY
echo "Build process started"

. ../config
. lib/lib.sh

[ -f "/usr/local/bin/rsync" ] || err 1 "Please install rsync packages"

# prepare dir
for _dir in $FRENZY_DIR $FRENZY_CD $FRENZY_FS $FRENZY_BUILD $SRCDIR ${OBJDIR} ${BOOTDIR} ${TMPDIR} ${FRENZY_ISO}; do
prepdir ${_dir}
done

prepdir ${FRENZY_DIR}/boot/skel/etc
prepdir ${FRENZY_DIR}/pkglite/locales

# prepare locale
if [ ${FRENZY_LANG} = "en" ]; then
rsync -avz pkglite/locales/locales.en ${FRENZY_DIR}/pkglite/locales/locales
rsync -avz boot/skel/etc/rc_en ${FRENZY_DIR}/boot/skel/etc/rc
fi

if [ ${FRENZY_LANG} = "ru" ]; then
rsync -avz pkglite/locales/locales.ru ${FRENZY_DIR}/pkglite/locales/locales
rsync -avz boot/skel/etc/rc_ru ${FRENZY_DIR}/boot/skel/etc/rc
fi

prepdir ${FRENZY_DIR}/systemroot/root/.fluxbox
# translating menu
for lng in en ru
do
(cd tools/mkmenu && ./mkmenu ${lng} ${FRENZY_TYPE} > ${TMPDIR}/menu.${lng})
mv ${TMPDIR}/menu.${lng} ${FRENZY_DIR}/systemroot/root/.fluxbox/
done

prepdir ${FRENZY_DIR}/root/.fluxbox
rsync -avz ${FRENZY_DIR}/systemroot/root/.fluxbox/menu.${FRENZY_LANG} ${FRENZY_DIR}/systemroot/root/.fluxbox/menu

stage_done
```
понятно с правками в обоих, а тут в N-сессии редактора некий шибко умный макрос отключил нам колорер, после хрен знает что наменял и восстановил неизвестно какое состояние колорера и вдогонку глобально схему расцветки сменил, мы этого не знаем, видим "ошибки", правим, а опосля гоняенмся с дубиной за тем гением который нам всю эту подлянку подстроил.

Я сей типовой сценарий привёл к тому, что решение предлагаемое **z0hm** годится для ситуации "_один редактор, одна активная задача_", а когда типовой сценарий работы "_одна копия шелла, несколько активных редакторов_" это решение самый верный способ дров наломать ибо тогда лучше никак или как сейчас, но этой возможностью не пользоваться, чем предлагаемое минималистическое:

> Если возможно: дополнить текущую команду установки статуса также и возвратом предыдущего состояния: res,prev_status = Plugin.SyncCall(ColorerGuid,"status",new_status)
> Виктора не слушать - такие огороды не нужны. 

Тут вспоминается один знакомый (имени незывать не стану) и его слова "_Process Hacker-ом должна пользоваться кухарка, а ей функции отладки, просмотра памяти процессов и прочие не нужны!_" - подход и рассуждения в чём-то схожи - "У меня задачи простые, значит всех под мою гребёнку!" а это ошибка в рассуждениях....

**Comment by ctapmex** [comment]
мужики не ссорьтесь. с праздником вас -)
вариант подходит
`res,prev_status = Plugin.SyncCall(ColorerGuid,"status",new_status)`
никто не заставляет использовать  prev_status. да и если ты запилил себе такой макрос и вызываешь его везде - то проблемы на твоей совести.

отличная идея по отключению раскраски в рамках текущего редактора, а не глобально. надо будет добавить пункт в меню и макрос. действовать будет в рамках текущего сеанса far.

**Comment by ctapmex** [comment]
#21

**Comment by VictorVG** [comment]
@ctapmex 

Взимно  всех с праздником! 

А реализовать сохранение режима в случае когда задача длительна по времени (я встретился с этим при разборе логов испытаних аппаратуры - там по времени накопление данных может занимать несколько месяцев, особенно коли это госиспытания при сдаче проекта - кто можент сказать где и в каких условиях будет работать оборудование, а по ТЗ типичный температурный диапазон выдают -85/+150, и это не считая ударных нагрузок до 350 - 400g а иногда и выше, и прочих далеко не самых благоприятных условий. Вот и крутимся. Сначала ломаю голову а как это реализовать ибо порой требования заказчика диаметрольно противоположны, а после испытания где всё проверятся т.к. выдвигаемые заказчиком требования по надёжности всегда сверх жёсткие, а значит нужно проверять самые неправдоподобные варианты. Ну и объём логов с приборов огромен, потому без раскраски просто просмотреть их - легко пропустить что-то важное и колорер выручает.) нетрудно к примеру сбросом флага в файл .conf  из макроса через тот же редатор.:)
