### ISSUE TITLE
Идея: добавить цифровой индекс 0 для вызова команды status плагина

### ISSUE THREAD

**Issue by VictorVG** [colorer/FarColorer#20]
Собственно идея в заголовке - добавить цифровой индекс 0 для вызова Plugin.Call(ColorerMainGUID,"status".[0|1]) и возвращать значение состояния On|Off плагина . А почему бы и нет если это будет не трудно? 

Что мы тут получим - упрощение макросов т.к. формат команды вызова плагина становится более единообразным Plugin.Call("D2F36B62-A470-418d-83A3-ED7A3710E5B5",<digit>[,<digit>])?

**Comment by VictorVG** [comment]
Уточнил. Перебор с усталости.

**Comment by z0hm** [comment]
Plugin.Call("D2F36B62-A470-418d-83A3-ED7A3710E5B5","status") возвращает статус состояния, а не выполнения. А вот уже Plugin.Call("D2F36B62-A470-418d-83A3-ED7A3710E5B5","status",true|false) возвращают статус выполнения - true. Plugin.Call("D2F36B62-A470-418d-83A3-ED7A3710E5B5",0) выводит меню и это правильно.

**Comment by VictorVG** [comment]
Верно, аналогичный результат даст и Plugin.Menu("D2F36B62-A470-418d-83A3-ED7A3710E5B5","45453CAC-499D-4B37-82B8-0A77F7BD087C"), но я к тому, чтобы добавить вызов команды Plugin.Call("D2F36B62-A470-418d-83A3-ED7A3710E5B5","status") в стиле остальных команд меню плагина, хотя это скорее идея из серии "А может попробуем?". Короче тут думать надо а нужно ли это. Когда писал был уверен что нужно, а сейчас и сам не пойму....

**Comment by VictorVG** [comment]
Разумно, ибо сама идея сыра до безобразия...
