### ISSUE TITLE
расширенный вариант смены статуса

### ISSUE THREAD

**Issue by ctapmex** [colorer/FarColorer#21]
Если возможно: дополнить текущую команду установки статуса также и возвратом предыдущего состояния: res,prev_status = Plugin.SyncCall(ColorerGuid,"status",new_status)
Виктора не слушать - такие огороды не нужны.

**Comment by z0hm** [comment]
Мне нужно глобально, чтобы не тыркаться в каждом открываемом редакторе. Можно добавить флаг режима - `mode` глобально/локально (по умолчанию (отсутствует, либо nil) - глобально, потому что в настройках так было всегда)):
`res,prev_status,prev_mode = Plugin.SyncCall(ColorerGuid,"status",new_status,mode)`

**Comment by VictorVG** [comment]
Повторюсь снова для того, чтобы мы могли лучше ориентироваться в явлениях:

режим  глобально "оптом для всех" применим только если у нас будет ситуация "одна копия Far - один редактор" и главное небольшие тексты на несколько строк считываемые глазом как единая картинка (в среднем человек одним взглядом читает 5 - 6 строк 80 колонного текста - до 500 символов) , в любом ином случае вероятность неосознания данных особенно на длинных или сложно формативанных текстах стремится к 100% т.к. это особенность человеческого мозга что при чтении он оперирует только с тем фрагментом который был прочитан последним, всё остальное в этот момент как бы "забывается" уходя на второй план, а при сложном форматировании текста резко возрастает утомляемость зрения что приводит к уменьшению размера воспринимаемого текстового поля и замедлению чтения. 

@z0hm 

Что касается 

> Хранить их для каждого открытого редактора - оно надо? - Имхо об этом должен помнить сам макросописатель.

это снова попытка свести задачу к частному случаю

> Мне нужно глобально, чтобы не тыркаться в каждом открываемом редакторе.

я же предлагаю отталкиваться не от частного, а от общего, а общее это несколько открытых редакторов с разными файлами для каждого из которых используется свой режим работы, а значит если следовать твоей логике макрос, т.е. локальный контур управления должен обладать полным набором информации о состоянии других выполняемых в данной сессии Far задачах, а это ему не позволят схемы контроля ЦП выдачей исключения 0x00000005 - Access Violation, так что предлагаемое тобой решение не реализуемо.

Что касается параметра _mode_ - разумная идея, только я бы её расширил так, чтобы получить максимальную универсальность решения при минимальной сложности - _mode_ битовый флаг типа операции, двух битовое поле, бит LOCAL=1 имеет приоритет относительно бита GLOBAL., по умолчанию если GLOBAL=0 и LOCAL=0 используется режим GLOBAL, дополнительной опции задающей приоритет режима нет.

Биты:

0 - GLOBAL
1 - LOCAL

Значения битов логические, True - сохранять/восстанавливать предыдущее (сохранённое) состояние, False - нет. Биты связаны логическим отношением: GLOBAL определяет режим если LOCAL=0, если LOCAL=1 режим определяет он.

Таким образом если мы по ошибке установим (LOCAL&GLOBAL) = 1 работаем в режиме LOCAL, при LOCAL = 0 и GLOBAL = 1 работаем в режиме GLOBAL, LOCAL=1 работаем в режиме LOCAL. 

Так сохраняется совместимость со старым поведением - всё меняется глобально, и появляется возможность управлять плагином в конкретной сессии редактора не портя рабочий процесс в остальных.

Я считаю, что такое решение на данном этапе оптимально.

**Comment by z0hm** [comment]
Зачем 2 флага, если 2 состояния? mode= false, oн же nil - глобально, true - локально в этом редакторе.

**Comment by VictorVG** [comment]
Да, пожалуй ты прав, однобитного флага хватит. Просто ты не смог обосновать свою мысль, но прав - всё же привязано ко времени. Если мы к примеру имели цепь состояний 1 = ON - 2 = ON -3 = OFF - 4 =OFF -5 ON, то восстанавливать состояние 1 или 3 находясь в состоянии 2 либо 4 нет смысла, а восстанавливать состоние 1 или 2 в состояниях 3 или 4 есть, и момент записи нам не важен. 

Согласен. Тут надо было посмотреть не на операции, а на цепочку событий, а момент фиксации состояния и файл можно определить средствами макроса. 

Единственное применение где можно было говорить о паре текущий/предыдущий это анализ состояний в макросе, но если он сохранит метку времени фиксации, то и сам может сохранить стек состояний произвольной глубины, так что  и с этой стороны идея работы с двумя последними состояниями явно избыточна, и максимум о чём можно думать это о записи состояния в виде строки с меткой времени для того, чтобы после макрос мог достать из БД любое произвольное значение и установить его. Но и это он сам по идее может сделать. Так что тут я с тобой согласен в том что лучше сделать минимальную систему базовых команд, а всё остальное реализовавать  через них типа  того как сделано в RISC ЦП - у них аппаратно релизуется базовый набор инструкций, всё остальное программно на их основе. А то выходит монстр типа CISC ЦП - куча команд на все случаи жизни, а многие из них применяются по случаю и только усложняют ЦП, ну и общее быстродействие по сравнению с RISC снижают в несколько раз - плата за универсальность.

**Comment by VictorVG** [comment]
Так что предлагаю такую общую формулировку:

общий формат команды  вызова плагина

 _Plugin.SyncCall(ColorerGuid,"status",[operation], mode)_ , 

где поля operation и mode могут принимать одно значение из:

operation - (True|1|On) - Enable , (False|0|Off) - Disable, Save - сохранить текущий статус, Rest - восстановить сохранённое значение, (Read|<пусто>) - прочитать текущий статус;

mode -  (False|nil|0| опущен) - глобально, он же режим по умолчанию , (True|1) - локально в текущем редакторе

вроде ничего лишнего, и ничего не упустили?

**Comment by z0hm** [comment]
Предлагаю так:
**res,prev_status = Plugin.SyncCall(ColorerGuid,"status",new_status,mode)**
**Save/Restore** не требуются, так как плаг возвращает статус перед его изменением. **new_status** и **mode** могут принимать значения **true/false/nil**, либо отсутствовать - в этом случае плаг возвращает статус без его изменения.

**Comment by VictorVG** [comment]
Погоди, дядь, не совсем понимаю твою идею в части:

> **Save/Restore** не требуются, так как плаг возвращает статус перед его изменением.. 

Как согласно ей должен сработать механизм сохранения состояния если в данный момент по алгоритму изменение не требуется, а фиксация состояния нужна? 

Ведь согласно её если в момент T0 мы имели некое состояние и согласно алгоритму управления нам нужно его сохранить именно средствами плагина (почему не важно - надо) значит мы должны выполнить далеко **не очевидную и очень не безобидную с точки зрения скрытых ошибок управляемой системы последовательность операций**:

_Declare var(bin) false
Declare tst(bin) false
var=read(status)
tst=not(var)
ColorerCommand(status,tst,mode)
ColorerCommand(status,var,mode)
var=false
tst=false_
   
а я ещё с института помню слова академика Воронова на его лекции по ТАУ (Теория Автоматического Управления) 

> _Если в цепи событий управления есть какая-то даже малейшая неочевидность, то с вероятностью стремящейся к единице она станет причиной критических сбоев всей системы в целом, и предотвратить это можно только устранив данную неочевидность как их первопричину. Иного способа нет, по крайней меня сегодня мы его не знаем._

Потому я лично считаю, что пусть набор команд будет на пару операций больше, зато мы исключим любые неочевидности и порождаемые ими цепи событий с непредсказуемыми последствиями.

**Comment by z0hm** [comment]
Если требуется фиксация состояния **средствами плагина**, то да, Save/Restore нужны, но зачем это нужно - непонятно. Поскольку плаг при изменении состояния сообщает его предыдущее значение, то фиксацию может выполнить внешний, обращающийся к API плагина код, в данном случае lua. Или Вы таймкапсулу всех-всех-всех настроек и состояния сабжа хотите?

**Comment by VictorVG** [comment]
Правильно, если можно где-то заложить неопределённость это надо сделать ибо реализуется элементарно! Ну, тогда ничего менять не надо твоя хотелка и так существует, а я устал.

**Comment by VictorVG** [comment]
@z0hm 

> Save/Restore не требуются, так как плаг возвращает статус перед его изменением

кто писал? И когда было показано, что сохранение с изменением состояния это частный случай , ты придумываешь какую-то мифическую таймкапсулу.  Хорошо, реализуем твои персональные хотелки в полном объёме - только глобально, предыдущий статус возвращается только при его изменении ибо лично тебе более ничего не надо, а значит ничего не случится.:lol: Говорю сразу - довожу твоё предложение до абсурда.

Что имеем с гуся:

В _копии №1 запросили состояние - что-то получили, сохранили, переключились в копию №2, позвали скрипт тот прочитал свои настройки, ага! а тут записано состояние!, загрузил и в копии №2 наломал дров ибо будучи написан под твою модель "_у меня одна копия редактора, потому мне нужно глобально!_" скрипт не учёл что вызван из копии №2 ибо для него её просто не существует!, наломал дров, а вот откатить наломанное им ни-з-з-зя ибо это таймкапсула, а значит не нужно!_

А раз так, то оставляем твой вариант - LOAD/SAVE, mode в печку, реализация по принципу "_не пойми что!_". Быть по сему ибо это таймкапсула.:)

**Comment by VictorVG** [comment]
Save/Restore не требуются, так как плаг **возвращает статус** перед его изменением

ключевое - **перед изменением** , а я тут попросил коллег собрать статистку как часто у них происходят такие изменения как отключение колорера и сколь часто они привязываются к его стоянию в других задачах? И их ответ (ответили 18 человек): 

> временное отключение колорера - 3% случаев, привязка в других алгоритмах к текущему статусу колорера 62% случаев, необходимость изменения статуса скриптом 0,2% случаев
> 
> _желательные/нужные им для работы возможности:_
> 
> возможность прочитать /сохранить предыдущее состояние статуса средствами плагина - желательно, но можно обойтись;
> возможность прочитать /сохранить текущее состояние статуса без его изменения средствами плагина - необходимо, что значительно упростит применяемые ими многократно вложенные скрипты управления.
> временное отключение колорера - 3% случаев, привязка в других алгоритмах к текущему статусу колорера 62% случаев, необходимость изменения статуса скриптом 0,2% случаев
> 
> работаем только с одной копией редактора и нас устраивает глобальное управление колорером? - и в кошмарном сне не приснится!
>
> _желательные/нужные для работы возможности?_
> 
> прочитать /сохранить предыдущее состояние статуса средствами плагина? - желательно, но можно обойтись;
> прочитать /сохранить текущее состояние статуса без его изменения средствами плагина? - необходимо, это значительно упростит наши скрипты

думаю, что всё и так понятно ибо статистика штука упрямая.

**Comment by z0hm** [comment]
Витя, я тебя ни разу не understand. - Кто мешает скрипту сохранять вместе с состоянием, id редактора?

`прочитать /сохранить предыдущее состояние статуса средствами плагина?` - Зачем плагу помнить предыдущее состояние? Когда мы делаем запрос состояния, либо его изменения, плаг нам вернёт состояние перед изменением, а дальше мы его можем хоть 1000 раз запоминать, клонировать и пр.

**Comment by VictorVG** [comment]
Судя по тому, что мне показали ребята правы - сложность алгоритма. У них там с полсотни редакторов и каждый смотрит свой прибор, плюс управление всей кучей. Но, **коли лично тебе это не нужно, то пусть все на ушах стоят из-за твоего персонального упрямства, а я пойду искать иное решение ибо ты решил что только как ты или никак. Быть по сему. Делай что хочешь, но после не жалуйся.**

**Comment by VictorVG** [comment]
Ну, или я дурак или ты издеваешься! А ты думаешь что их скрипты столь же просты как твои? **Они  сейчас вынужденны это делать и прямо говорят что им это чудовищно мешает**, но ты демонстративно "_Наша ваша не понимаша! Наша ваша измора взятя!_ ". 

Смотрю, а как говаривал мой дед "_Читаю книгу, но вижу фигу!_" и демонстративно под благовидным предлогом "Упрощение разработки плагина!" добиваешься "_А не пошли бы вы господа  ... в другое место договариваться! Утомили!_". А этим, помяни моё слово всё и кончится...

**Comment by z0hm** [comment]
Нужно save/restore - я не против, я против быть не могу по определению - оно же мне мешать никак не может, поскольку это другая команда, либо её параметр! Чем мне может мешать **Plugin.SyncCall(ColorerGuid,"SaveStatus")** или **Plugin.SyncCall(ColorerGuid,"RestoreStatus")** ??? Или не устраивает бинарный параметр **new_status**, который ты хочешь сделать int, чтобы поместить в него и save/restore?

**Comment by VictorVG** [comment]
Тут ты пожалуй заметил невязку. Смотри что я вижу:

тот вариант который я описал _Plugin.SyncCall(ColorerGuid,"status",[operation], mode)_ если мы развернём команду выглядит у нас так:

_Plugin.SyncCall(ColorerGuid,"status","load", mode)
Plugin.SyncCall(ColorerGuid,"status","save", mode) 
Plugin.SyncCall(ColorerGuid,"status",, mode)  
Plugin.SyncCall(ColorerGuid,"status","read", mode) 
Plugin.SyncCall(ColorerGuid,"status",true, mode) 
Plugin.SyncCall(ColorerGuid,"status",false, mode) ,_

т.е. третье поле код операции (КОП) и одновременно логическое, символьное или цифровое значение, либо пустое в зависимости от реализации. Если писать машинную команду, то при его переводе на уровень микрокода получаем дополнительные три ветви алгоритма входного  фильтра для парсера этого поля:
```
if type(field) == char then lbl1 end;
 if type(field) == logical then lbl2 end;
  if type(field) == int then lbl3 end;
   if type(field) =="" then 
      begin 
         field = read
          goto lbl1
        end;
     else field = read
        end;
lbl1: if field == "" then goto lbl... end
.....
goto next:
lbl2: : if field == "" then goto lbl... end
....
goto next
lbl3: : if field == "" then goto lbl... end
....
next:
```
при этом последний фильтр в цепочке работает по логике "_если команда не распознана, считать её read_" что необходимо для исключения влияния входных помех. Плюс нужна некая логика распознания типа, а это затратно раз, и чревато ошибками два. В микрокоде это выльется в лишнее ALU и такты. А оно мне надо? 

Потому упрощаем наш набор до минимума:

_Plugin.SyncCall(ColorerGuid,"status","l", mode) - LOAD
Plugin.SyncCall(ColorerGuid,"status","s", mode) - SAVE
Plugin.SyncCall(ColorerGuid,"status","r", mode) - READ
Plugin.SyncCall(ColorerGuid,"status","e", mode) - ENABLE
Plugin.SyncCall(ColorerGuid,"status","d", mode) - DISABLE_

говорим:

1) поле field обязательное и опускать его нельзя;
2) поле field должно быть либо типом Char(1) либо Digital поскольку тип Logical не позволяет передать более двух значений на бит, а при использовании трёх бит для обозначения всех возможных комбинаций проще использовать числа;
3) человек может использовать полное или сокращённое имя команды, но декодер команд смотрит только её первую букву.
4) Флаг mode - Integer(1), значения: 0 - локальная операция , 1 - глобальная.

вот теперь всё, мы упростили ТЗ, устранили все возможные места сбоев декодера команд и более тут трогать нечего!

**Comment by z0hm** [comment]
Зачем наворачивать такие сложности? - Я предложил простой, принятый в АПИ фара подход. Скрипты любой сложности **элементарно** смогут с этими командами работать.

**Comment by VictorVG** [comment]
> Что возвращает read? У меня возвращённый status можно просто передать обратно. 

а что он может вернуть? VALUE и его можно вернуть обратно.

>  У тебя же нужна логика для выбора 3-го аргумента, а раз так, то не составит и труда её использовать для выбора 2-го аргумента Plugin.Call(). Также в моём варианте можно опускать аргументы, тогда они читаются как nil, что эквивалентно false и при этом всё работает логично и правильно. 

Опускание аргументов требует дополнительных шагов анализа "_на пусто_" и сокращает число шагов разбора только если они последние в цепочке.  В таком случае мы просто не меняем последние значения заданные при инициализации в массиве параметров, в противном же случае мы должны сравнить значение в ячейке с обнаруженным и если оно не совпадает переписать её, если пусто должны пропустить операцию изменения.

> Главный вопрос - мы запускаем колорер на х86 или абаке, что нужна фиксация количества аргументов? 

В дискретной математике есть только три базовых битовых операции AND , NOT , OR, а все остальные реализуются их комбинациями. И не важно как называется система ("чёрный ящик") реализующая набор выходных реакций (ответов) в зависимости от набора входных ибо в конечном итоге всё сведётся к эти трём базовым операциям. 

Нам проще оперировать понятием "чёрного ящика" оговорив что каждому набору входных сигналов (параметру) соответствует только один ответ и не лезть в то, как он устроен, но коли тебе это будет для себя интересно, то найди любой учебник по дисциплине _Основы Дискретной Математики (ОДМ)_ , хотя предупрежу сразу словами нашего преподавателя по ней доцента Александра Григорьевича Кисунько "_Я могу дать вам список из сотен книг по ОДМ, но вы в них запутаетесь, но вам будет проще понять ОДМ по моим лекциям._" которые он произнёс на первой лекции по ОДМ когда у нас в расписании пятого семестра (первый семестр третьего курса института) появился этот предмет. И для начала он подкинул нам задачу "_Попробуйте нарисовать четырёхмерный булев куб существующий момент времени T._" - скажу сразу никто из нас её решить не смог так как нам привычно трёхмерное пространство имеющее _ширину, длину, высоту_, а четырёх мерное - а что это такое?

**Comment by z0hm** [comment]
Слишком много текста не по теме. API Far'a использует схожий, как в моём варианте, подход. Сокращение числа операций на этапе обработки входных параметров ничто, по сравнению со временем исполнения.

**Comment by VictorVG** [comment]
> Слишком много текста не по теме. API Far'a использует схожий, как в моём варианте, подход. Сокращение числа операций на этапе обработки входных параметров ничто, по сравнению со временем исполнения.

нежелание думать не отменяет сей необходимости :)

Думаю стоит оставить окончательное решение за тем, кто будет реализовывать. Если будет принято решение использовать вариант Виктора, то пожелание не сокращать до команды до одной буквы - пусть будут полностью, иначе не наглядно.

А я не говорю о сокращении записи названия команды -  используя (кстати это абсолютно  стандартный приём) _метод выборки по шорткату_ в качестве которого назначается произвольная  буква имени команды мы допускаем возможность выбора из ряда ключевых слов и тут есть свой подводный камень - при такой проверке имеется отличная от нуля вероятность ошибочного распознания в качестве команды произвольного слова содержащего ключевую букву в анализируемой позиции, даже ошибочную.

> Слишком много текста не по теме.

не делай вид что не понимаешь что говорят добиваясь реализации "_только так, как мая левая нога хочет!_"

**Comment by z0hm** [comment]
Открываем энциклопедию фара и внимательно смотрим, какой стиль в АПИ используют разработчики фара.

**Comment by VictorVG** [comment]
Всё, караул устал. Стой на ушах, но других не трогай!

**Comment by VictorVG** [comment]
От инца отписался ибо Лёха открыто издевается.

**Comment by ctapmex** [comment]
добавлено новое api
