### ISSUE TITLE
не работает раскраска

### ISSUE THREAD

**Issue by ctapmex** [colorer/FarColorer#22]
Обнаружил в Far 3.0 некорректное поведение плагина FarColorer на файлах большого размера (1,5-2Мб). Если при редактировании курсор стоит в конце файла, то колорер не раскрашивает текст. Если начать листать файл вверх кнопкой PageUp, то в определенный момент происходит затуп и начинается раскраска всего текста. Также при редактировании не работает перемещение курсора по колесу мыши. Far 2.0 обрабатывает такие файлы корректно.

**Comment by ctapmex** [comment]
проблема в удалении KEY_IDLE в far http://forum.farmanager.com/viewtopic.php?p=128666#p128666

временное решение - вызов из меню/макроса принудительной раскраски всего файла

**Comment by ctapmex** [comment]
зависит от #24

**Comment by VictorVG** [comment]
Кстати это ловится и на HTML, когда открываю первый попавшийся файл - раскраска сюань, зову Plugin.Call(ColorerGUID,5) выбираю тип раскраски HTML - текст визуально не раскрашен, прокрутка или MsWhellClick - раскрасились.  Не раз с таким встречался, но сейчас не могу с ходу подобрать файл-пример - выходит я их уже привёл в порядок(?).

**Comment by ctapmex** [comment]
не актуально. исправлено в начале 2019
