### ISSUE TITLE
Duplicate entries in outliner

### ISSUE THREAD

**Issue by plastikat** [colorer/FarColorer#25]
_Windows 8.1 x86
Far 3.0.4882
FarColorer 1.2.8 (build 1)_

I believe there's some bug in outliner code that's been very annoying for quite a while, but I just couldn't grasp the steps to reproduce it. Finally I have managed to do so. Now, here are the steps:

- Create a file test.py with this content (with a newline after 'pass'):
```
def outliner_bug_test():
	pass
```

- Open the file and check the outliner: it displays a single function entry. Now go to the end of file, press BS to move the cursor to the end of `pass` statement and check the outliner: now there are two duplicate entries.
- If you press Enter (to effectively revert the changes made) you'll get more dupes.

When I change some file a lot, adding and removing functions (when there are many of them in total) I sometimes get some entries duplicated multiple times (up to 10 maybe or even more) and end up with a cluttered outliner. Under some circumstances they sometimes go away on itself (I haven't grasped the actions), but usually they don't and I have to close and re-open the file to get rid of the dupes - losing undo history on the way. I hope this information helps and you can do something about it.

**Comment by 2underscores-vic** [comment]
Confirm it.

**Comment by ctapmex** [comment]
fixed in 1.3.2
