### ISSUE TITLE
FarColorer Javascript backtick quotes....

### ISSUE THREAD

**Issue by d3x0r** [colorer/FarColorer#26]
http://forum.farmanager.com/viewtopic.php?f=39&t=4319&p=144380#p144380

would be nice if javascript coloring supported backtick quotes...

This line is especially bad.

	var db = Gun( {prefix: 'generator/', peers: [`ws://${location.host}/gun`]} ).get( "Voxelarium" );

the open backet causes color errors afterward because it never see the close; because the link // looks like a comment.

**Comment by d07RiV** [comment]
Ran into this issue as well. I made a pull request here: https://github.com/colorer/Colorer-schemes/pull/60

You can replace the jScript.hrc file in your Plugins\FarColorer\base\hrc\common.jar\inet folder with the one in that PR.

**Comment by d3x0r** [comment]
Thank you :) That seems to work.

**Comment by ctapmex** [comment]
fixed in Colorer-schemes

**Comment by d3x0r** [comment]
Yay!  When is it going to be 'hot off the press' ?

**Comment by ctapmex** [comment]
in far3 since 2019
