### ISSUE TITLE
Медленно работает раскраска длинных слов в логах

### ISSUE THREAD

**Issue by excitoon** [colorer/FarColorer#28]
Больше информации чуть ниже в тикете.

А пока - тестовый файл.
[1.log](https://github.com/colorer/FarColorer/files/2749846/1.log)

**Comment by excitoon** [comment]
И в `txt` тоже.

**Comment by ctapmex** [comment]
проблема известная. как фиксация в багтрекере  пойдет. но обнадеживать не буду, планов исправления нет

**Comment by ctapmex** [comment]
решено в 1.3.13
