### ISSUE TITLE
падение при наличии одинаковых prototype name в My.hrc

### ISSUE THREAD

**Issue by z0hm** [colorer/FarColorer#34]
hrc\auto\My.hrc
....
  <prototype name="lua" group="My" description="lua,moon">
    <location link="jar:common.jar!base/lua.hrc"/>
    <filename>/\.(moon)$/i</filename>
  </prototype>
  <prototype name="lua" group="My" description="lua,moon">
    <location link="jar:../common.jar!base/lua.hrc"/>
    <filename>/\.(tmp)$|^far\.x+\.(cmd)$/i</filename>
    <firstline>/^\-\- lua|^lua:/</firstline>
  </prototype>

Задача раскрасить как lua в редакторе:
1. *.moon как *.lua - лучше так, чем никак
2. *.tmp и far.xxxxxx.cmd с 1-ой строкой -- lua, или lua:

Если свести в одну секцию:
  <prototype name="lua" group="My" description="lua,moon">
    <location link="jar:../common.jar!base/lua.hrc"/>
    <filename>/\.(w?lua|moon|tmp)$|^far\.x+\.(cmd)$/i</filename>
    <firstline>/^\-\- lua|^lua:/</firstline>
  </prototype>
, то не падаем, но и не красим *.lua с 1-ой строкой, начинающейся на 3 и более минусов.

**Comment by z0hm** [comment]
Перенёс на ruboard 
https://forum.ru-board.com/topic.cgi?forum=5&topic=50439&start=1020#16

**Comment by z0hm** [comment]
https://forum.ru-board.com/topic.cgi?forum=5&topic=50439&start=1020#18
Ответа не дождался

**Comment by ctapmex** [comment]
надо освежить знания, отвечу позднее

**Comment by ctapmex** [comment]
ответил http://forum.ru-board.com/topic.cgi?forum=5&topic=50439&start=1080#16

да, совсем забыл , что имя прототипа должно всегда быть равно имени типа в hrc файле. поэтому вариант с двумя прототипами, ссылающимися на одну схему  работать не будет.
 
решение поставленной задачи
`<prototype name="lua" group="My" description="lua">
    <location link="jar:../common.jar!base/lua.hrc"/>
    <filename>/\.(w?lua)$/i</filename>
    <filename>/\.(moon)$/i</filename>
    <filename  weight='0.5'>/\.(tmp)$/i</filename>
    <firstline>/^\-\- lua|^lua:/</firstline>
</prototype>`

нельзя логически задать условие 'если имя такое и файл начинается с то..., а для других случаев '. но можно с помощью веса отрегулировать подсчет общего веса

**Comment by z0hm** [comment]
1. Почему нельзя в общем случае? - Регэксп матчится, значит true, не матчится, значит false.

2. Из решения непонятно к какому filename относится необходимость иметь firstline - к предыдущему? А если он не один? - Например нужен ещё и <filename>/^far\.x+\.(cmd)$/i</filename>

3. Weight теперь в пределах 0..1? Раньше было 1-10 целыми, или путаю?

**Comment by ctapmex** [comment]
изначально логика сопоставления прототипа к файлу строилась как  определение максимальной суммы весов сработавших filename и firstline. брались все эти объекты , привязанные к прототипу. не было и нет сейчас группировки.
вес для filename по умолчанию 1, а для firstline 2. 
вес можно указать любой не отрицательный. целое или вещественное число. 
тут указал 0.5 , чтобы выбор lua был при совпадении минимум двух условий, если вдруг есть другой прототип с маской tmp

**Comment by z0hm** [comment]
4. 1.tmp с содержимым "-- lua\nprint()" красит неверно, выбирает предыдущую схему My-js, lua в группе My отсутствует.

**Comment by ctapmex** [comment]
я не знаю что за схема My-js, и какие в ней настройки. приведенный мной пример работает на штатных схемах. Если у вас есть свои схемы, то надо адаптировать вес под них

**Comment by z0hm** [comment]
Да, firstline weight='10' побеждает, выбирается при этом группа Favorites-lua, хотя согласно прототипа ожидаю My-lua, но, как говорил выше lua в My отсутствует при вашем прототипе. Красит правильно, спасибо.

**Comment by ctapmex** [comment]
падение исправил в 1.3.19
