### ISSUE TITLE
Фриз и последующее падение при FarExit при наличии FarColorer 1.3.17

### ISSUE THREAD

**Issue by VictorVG** [colorer/FarColorer#37]
ОС Win7 SP1 x64, и5645 выполняю произвольные операции, в т.ч. в редакторе, выхожу - фриз с видимыми часами в правом углу и курсором в левом углу нижнем углу окна десктопа фар-а секунд на 15 - 20, после чего ОС молча снимает задачу фар-а. Потому, хотя за день это видел уже несколько раз не мог понять где искать, но предполагаю, что это ещё одно проявление Мантис #0003811. 

Пока так же откатил колорер на корретно работавшую версию 1.3.15 взяв её из своего архива, а проверять буду утром - сейчас на часах 02:52:34 +0300 , понятно что генерал Храповицкий уже  в во все трубы трубит.:)

**Comment by skipik** [comment]
У меня тоже падать стало после F10 - Enter.
Есть дамп фара, если нужен - скину.

**Comment by VictorVG** [comment]
С 1.3.15 ошибка не воспроизводится, значит стоит смотреть изменения 1.3.16 - 13.17

**Comment by ctapmex** [comment]
в чем дело понятно, надо заняться.

**Comment by VictorVG** [comment]
Главное, что эта информация помогла.

**Comment by VictorVG** [comment]
Соберу, посмю - вожусь пытаясь поправить в Process Hacker [*падение из-за устаревших плагинов*](https://github.com/processhacker/plugins-extra/issues/72) под Win 10 v2004+, а вышвыривать их не хочу. Костыль в инку в виде блокировки их установки прикрутить не долго, а надо ли? А коли и прикручу, так ещё и в инструкции (которые как обычно не читают :)) для архива сиё расписывать...

**Comment by VictorVG** [comment]
Пока возился-тестил и Мантис-0003812: работа api при выходе из far  посмотрел. Видимо его стоит уточнить - на мелких файлах far успевает закрыть фоновый редактор (колорер успел покрасить), на больших падаем. Я смотрел с парой - chagelog_eng из фар-а и логом LinX 0.9.7 (3164 байт) - если открыт лог, ошибки нет, ченжлог - упали.

Лог для теста подкинул

**Comment by VictorVG** [comment]
С делением на ноль очень интересно - видна процессорная зависимость явления "мощность ЦП - размер файла - вероятность падения" - если у i7-2600 один или несколько файлов размером 3 - 4 Кб проблемы не вызывают никаких проблем по ExitFar, то любой такой файл на i3-2120 гарантирует возникновение исключения. На i7-2600 падение возникло на файле в 15 Кб, а мелкие размером по 3 - 4 "мы не заметили", всё что больше - вызывает исследуемое явление...

**Comment by VictorVG** [comment]
С делением на ноль очень интересно - видна процессорная зависимость явления "_мощность ЦП - размер файла - вероятность падения_" - если у i7-2600 один или несколько файлов размером 3 - 4 Кб проблемы не вызывают никаких проблем по ExitFar, то любой такой файл на i3-2120 гарантирует возникновение исключения. На i7-2600 падение возникло на файле в 15 Кб, а мелкие размером по 3 - 4 "мы не заметили", всё что больше - вызывает исследуемое явление...

Ну, теперь остаётся дождаться мамки на Х79/Х97/С602 под Xeon 2667 и там глянуть минимальный размер файла который спровоцирует падение. Я ожидаю, что он должен быть несколько больше.
