### ISSUE TITLE
падение при выходе из far

### ISSUE THREAD

**Issue by ctapmex** [colorer/FarColorer#40]
https://bugs.farmanager.com/view.php?id=3812

**Comment by gurm4n** [comment]
Прошу прощения, что не по теме, но имеется ли возможность расширить базу подсвечивающихся слов?

**Comment by ctapmex** [comment]
да, возможно. необходимо править схемы .  предложения, баг и т.п. https://github.com/colorer/Colorer-schemes

**Comment by ctapmex** [comment]
fixed
