### ISSUE TITLE
bash, ломается разбор после s

### ISSUE THREAD

**Issue by z0hm** [colorer/FarColorer#42]
Похоже на руборде прошло незамеченным https://forum.ru-board.com/topic.cgi?forum=5&topic=50439&start=1180#12

Код: #!/bin/bash 
  
 if [ "$num" == "s" ]; then killap 
 elif [ "$num" == "z" -a $finish -lt $last ]; then page=$(($page+1)); oldnum=$num; shpage 
 elif [ "$num" == "a" -a $page -gt 0 ]; then page=$(($page-1)); oldnum=$num; shpage 
 fi 
  
 Если заменить в "$num" == "s" s какую-нибудь другую кроме s букву, то раскраска НЕ ломается.

**Comment by ctapmex** [comment]
duplicate - https://github.com/colorer/Colorer-schemes/issues/96
