### ISSUE TITLE
How do I use FarColorer?

### ISSUE THREAD

**Issue by ma-choo** [colorer/FarColorer#45]
I've enabled FarColorer and selected a theme through F9 - Options - Plugins configuration - FarColorer but my background remains blue. I can't find much documentation on FarColorer. How do I use this plugin?
![image](https://user-images.githubusercontent.com/14033754/107190446-d007c080-69b8-11eb-8486-3856cd2e2506.png)

**Comment by yegor-mialyk** [comment]
From your description it is not clear what colors you want to change.

FarColorer is a syntax highlighting plugin, which means it highlights files opened in the Far Manager's internal editor (F4).

If you want to change colors of entire Far Manager you should F9 -> Options -> Colors instead. While Far Manager color themes are available, there is no UI for them. You should go to %FARHOME\Addons\Colors and manually load themes (there is a how-to readme available in the Addons folder).
