### ISSUE TITLE
Вопрос - как собрать после изменений в 1.4.0? Ни инструкция, ни тулкит не работают - ругань в логе 

### ISSUE THREAD

**Issue by VictorVG** [colorer/FarColorer#46]
Вот лог тулкита работавшего до изменений:
```
Already up to date.
Submodule path 'external/vcpkg': checked out '56136ffae69a4a7f8b9cd5452713925417d47367'
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.9.34
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x86'
-- The CXX compiler identification is MSVC 19.16.27045.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/.../VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring incomplete, errors occurred!
See also "I:/Dev/Far3/2/FarColorer/build/Release/x86/CMakeFiles/CMakeOutput.log".
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.9.34
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
-- The CXX compiler identification is MSVC 19.16.27045.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/.../VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring incomplete, errors occurred!
See also "I:/Dev/Far3/2/FarColorer/build/Release/x64/CMakeFiles/CMakeOutput.log".

    colorerConfig.cmake                                                                                             0:42
    colorer-config.cmake

  Add the installation prefix of "colorer" to CMAKE_PREFIX_PATH or set
  "colorer_DIR" to a directory containing one of the above files.  If
  "colorer" provides a separate development package or SDK, be sure it has
  been installed.



Служебная программа обслуживания программ Microsoft (R), версия 14.16.27045.0
(C) Корпорация Майкрософт (Microsoft Corporation).  Все права защищены.

NMAKE : fatal error U1064: MAKEFILE не найден и конечный файл не задан
Stop.
Build type for FarColorer: Release
FarColorer configurations for IDE: Debug;Release
CMake Error at CMakeLists.txt:48 (find_package):
  Could not find a package configuration file provided by "colorer" with any
  of the following names:

    colorerConfig.cmake
    colorer-config.cmake

  Add the installation prefix of "colorer" to CMAKE_PREFIX_PATH or set
  "colorer_DIR" to a directory containing one of the above files.  If
  "colorer" provides a separate development package or SDK, be sure it has
  been installed.



Служебная программа обслуживания программ Microsoft (R), версия 14.16.27045.0
(C) Корпорация Майкрософт (Microsoft Corporation).  Все права защищены.

NMAKE : fatal error U1064: MAKEFILE не найден и конечный файл не задан
Stop.

The system is: Windows - 6.1.7601 - AMD64
Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
Compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017.../VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe
Build flags:
Id flags:

The output was:
0
Оптимизирующий компилятор Microsoft (R) C/C++ версии 19.16.27045 для x64
(C) Корпорация Майкрософт (Microsoft Corporation).  Все права защищены.

CMakeCXXCompilerId.cpp
Microsoft (R) Incremental Linker Version 14.16.27045.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:CMakeCXXCompilerId.exe
CMakeCXXCompilerId.obj


Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.exe"

Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.obj"

The CXX compiler identification is MSVC, found in "I:/Dev/Far3/2/FarColorer/build/Release/x64/CMakeFiles/3.19.6/CompilerIdCXX/CMakeCXXCompilerId.exe"

Detecting CXX compiler ABI info compiled with the following output:
Change Dir: I:/Dev/Far3/2/FarColorer/build/Release/x64/CMakeFiles/CMakeTmp

Run Build Command(s):nmake /nologo cmTC_a5cdc\fast && 	"C:\Program Files (x86)\Microsoft Visual Studio\2017\...\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\nmake.exe"  -f CMakeFiles\cmTC_a5cdc.dir\build.make /nologo -L                  CMakeFiles\cmTC_a5cdc.dir\build
Building CXX object CMakeFiles/cmTC_a5cdc.dir/CMakeCXXCompilerABI.cpp.obj
	C:\PROGRA~2\MIB055~1\2017\...\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @C:\Users\...\AppData\Local\Temp\nm9A83.tmp
CMakeCXXCompilerABI.cpp
Linking CXX executable cmTC_a5cdc.exe
	"C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_a5cdc.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\mt.exe --manifests -- C:\PROGRA~2\MIB055~1\2017\...\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\cmTC_a5cdc.dir\objects1.rsp @C:\Users\...\AppData\Local\Temp\nm9AE2.tmp
```
если собирать по инструкции в REAME.MD:
```
Download the source from git repository:

    git clone https://github.com/colorer/FarColorer.git --recursive

Setup vcpkg

    cd colorer-library
    ./external/vcpkg/bootstrap-vcpkg.bat

Build colorer and dependency, if they are not in the local cache:

    mkdir build
    cd build
    cmake -S .. -G "Visual Studio 16 2019" -DCMAKE_TOOLCHAIN_FILE=../external/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static -DVCPKG_OVERLAY_PORTS=../external/vcpkg-ports -DVCPKG_FEATURE_FLAGS=versions -DCOLORER_BUILD_ARCH=x64
    colorer.sln

For x86 platform use `-DVCPKG_TARGET_TRIPLET=x86-windows-static` and `-DCOLORER_BUILD_ARCH=x86`.
Once builded, the dependencies will be cached in the local cache.
```
 так же не выходит - каталога colorer-library в репозитории нет, если задать md colorer-library, то дальше возникает сбой на этапе генерации из-за ICL и ни майка, ни солюшена не создаётся. До 1.4.0 использовал такой тулкит: 
[FarColorer_toolkit_common.zip](https://github.com/colorer/FarColorer/files/6152428/FarColorer_toolkit_common.zip)

**Comment by ctapmex** [comment]
поправил README.md

**Comment by VictorVG** [comment]
Спасибо! Попробую.

**Comment by VictorVG** [comment]
Н-н-да... "Ставьте наш мусор! У вас на дисках ещё есть место которое мы не забили!" - питон 3.9 требует зависимости которых нет. Судя по логам всё ломает он:

[configure-x64-windows-static-rel-err.log](https://github.com/colorer/FarColorer/files/6155902/configure-x64-windows-static-rel-err.log)
[configure-x64-windows-static-rel-out.log](https://github.com/colorer/FarColorer/files/6155903/configure-x64-windows-static-rel-out.log)
[vcpkg-manifest-install.log](https://github.com/colorer/FarColorer/files/6155904/vcpkg-manifest-install.log)

**Comment by ctapmex** [comment]
ты сам пошел по пути ставить себе мусор -) иначе используй готовые сборки.
vcpkg - инструмент для сборки разнородных с++ библиотек по одинаковым правилам через cmake.  он позволяет не думать мне как собрать и интегрировать библиотеку себе в проект. Да, поскольку библиотеки собираются по разному, не все построены на cmake, vcpkg скачивает в свое окружение mingw/python и т.п.. В данном случае, для icu нужна сборка через mingw + python. Эта icu самая для меня проблемная, то что vcpkg решает это - супер.
еще по мусору - после успешной сборки  создается кэш, для переиспользования при следующих вызовах. Сюда сохраняет C:\Users\...\AppData\Local\vcpkg\archives\ . Кэш перестраивается если меняется версия любой компоненты, требующейся при сборке.

по текущей проблеме, проверь файл 
I:/Dev/Far3/2/FarColorer/external/vcpkg/downloads/tools/python/python-3.9.0-x64/python.exe , он запускается ? или так же требует библиотеку. 
у меня на разных машинах и в облаке github все заводится успешно.

**Comment by VictorVG** [comment]
Он её и просит - в семёрке сей либы нет. Попробую обновить рунтаймы, но ...

**Comment by data-man** [comment]
Можно попробовать `cmake -DCOLORER_USE_VCPKG=OFF`.

**Comment by ctapmex** [comment]
COLORER_USE_VCPKG=OFF предназначена в первую очередь для linux.
если её использовать на windows, то где то рядом уже должны лежать собранные зависимости.

**Comment by ctapmex** [comment]
VictorVG , это как обычно грабли использования старых операционок . Я не спорю, что 7 оптимальна для многих задач и т.п.. Но она снята с поддержки и разрабатывать под ней нет никакого желания.
да, надо попробовать поставить runtime.

**Comment by VictorVG** [comment]
У меня рабочий ChipCAD написан в первую очередь для Tru64 UNUX (DEC OSF/1) и FreeBSD, но ребята сделали его порт под Win7, и ставить модную десятку - становится невозможна разработка и иммиграционное моделирование электронных схем для чего данная CAD система была создана,  но и не он один отказывается работать в среде десятки из-за её постоянный "телеметрии", а десятки других портированных с Tru64 UNIX программ. Так что я в какой-то степени привязан к конкретной ОС прежде всего тем фактом, что там нет столь наглой утечки конфиденциальных данных какая идёт в десятке где закрыл одну дырку, а ось открывает десяток новых. Основная рабочая ОС для меня Tru64 UNIX/FreeBSD, а семёрка под ними крутится в виртуалке - её возможностей для работы систем CAD достаточно, а что на ней не бегают игрушки - так для отдыха мне и "пятнашки" в OSF/1 хватает ибо я ещё в 80-х наигрался в Doom, Retalator, F15
Gods, Viking, ZELIARD (это старые игры под DOS) про которые сейчас многие и не слышали, но если хочется то последнюю четвёрку могу прислать в архиве - там F15 штука интересная - проиграл, сбили - попал в Правду - американский пилот-террорист, выиграл - пьёшь в баре в компании друзей.:) Правда F15 идёт только в корне диска С:, но ей и PC/AT хватало.:)

**Comment by ctapmex** [comment]
Виктор, в итоге получилось собрать ?

**Comment by VictorVG** [comment]
Пока 1.3.24 пользу.сь. Новую ещё не пробовал из-за цепочки аварий, но попробую отдельно собрать.

**Comment by ctapmex** [comment]
поправить можно, но надо делать форк vcpkg, что очень, очень не хочется. Извини, но делать не буду, т.к. это повлечет дальнейшие приседания. И от былой экономии за счет унификации пойдет новая головная боль

**Comment by VictorVG** [comment]
Это понятно, тут не мы бал правим. Смиримся, что нам оставили?

**Comment by ctapmex** [comment]
тут тебе решать. -)

**Comment by VictorVG** [comment]
А что остаётся? Ещё и магистральный пров дров наломал с каналом 0 ряд сетевых протоколов сломал, когда починит сюань - звонили ему, но трубку не берут...
