### ISSUE TITLE
После Far b5765.1 вылез "подарок" от Мантис 3852 - полетели цвета

### ISSUE THREAD

**Issue by VictorVG** [colorer/FarColorer#48]
После эксперимента [**Mantis 3852**](https://bugs.farmanager.com/view.php?id=3852 ) в b5765 в режиме TrueMod полетели цвета раскраски URL для белой схемы- до был синий:

b5764, TrueMod == ON

![1](https://user-images.githubusercontent.com/906886/114020966-d4e1d700-9878-11eb-9907-c24fc7c4331d.png)

после , на примере b5777:

TrueMod == ON

![2](https://user-images.githubusercontent.com/906886/114021369-4ae63e00-9879-11eb-8039-79816ef493fd.png)

цвет URL стал серый,

TrueMod == OFF

![3](https://user-images.githubusercontent.com/906886/114021559-8123bd80-9879-11eb-9dec-8fae04d41715.png)

коричневый...

Как возможное решение я вижу задание в схемах для URL фиксированного цвета из палитры 16 цветов так, чтобы фар не искал "ближайший подходящий по мнению алгоритма", а ставил его. 

Но, хотя понятно что причина не в колорере, а в не удачном эксперименте в коде фара, я думаю, что и нам стоит про это знать и подкостылить т.к. не известно где этот или сходный эффект снова вылезет....

**Comment by VictorVG** [comment]
Частично откатил b5765.1 - только colormix.cpp , [**кинул на тест**](https://forum.ru-board.com/topic.cgi?forum=5&topic=50439&start=2180#3) - посмотрим что получится...

**Comment by ctapmex** [comment]
привет.
win 7 ?
что значит TrueMod == OFF/ON ? вкл/выкл в самом плагине или еще настройки окружения? используется обычная консоль или conemu?
какой именно цветовой стиль используется ? белый он ведь только для truemod .

я попробовал на новой версии фара в win10, даже нашел это файл из пример - все отображается как надо . настройки консоли винды по умолчанию , не менял цвета.

**Comment by VictorVG** [comment]
TrueMod включал/выключал в настройках плагина, консоль CMD, цветовой стиль белый. Вот настройки в XML:
```
		<plugin guid="D2F36B62-A470-418D-83A3-ED7A3710E5B5">
			<hierarchicalconfig>
				<key name="D2F36B62-A470-418D-83A3-ED7A3710E5B5" description="FarColorer">
					<value name="Catalog" type="text" value=""/>
					<value name="ChangeBgEditor" type="qword" value="0000000000000000"/>
					<value name="CrossDraw" type="qword" value="0000000000000002"/>
					<value name="CrossStyle" type="qword" value="0000000000000000"/>
					<value name="Enabled" type="qword" value="0000000000000001"/>
					<value name="HrdName" type="text" value="white"/>
					<value name="HrdNameTm" type="text" value="default"/>
					<value name="LogPath" type="text" value=""/>
					<value name="OldOutlineView" type="qword" value="0000000000000001"/>
					<value name="PairsDraw" type="qword" value="0000000000000001"/>
					<value name="SyntaxDraw" type="qword" value="0000000000000001"/>
					<value name="ThreadBuildPeriod" type="qword" value="00000000000000C8"/>
					<value name="TrueMod" type="qword" value="0000000000000001"/>
					<value name="UserHrcPath" type="text" value=""/>
					<value name="UserHrdPath" type="text" value=""/>
					<key name="HrcSettings">
						<key name="acapella"/>
						<key name="c"/>
						<key name="cpp"/>
						<key name="css"/>
						<key name="d"/>
						<key name="ddoc"/>
						<key name="default">
							<value name="backparse" type="text" value="60000"/>
						</key>
						<key name="diff"/>
						<key name="go"/>
						<key name="groovy"/>
						<key name="hrc"/>
						<key name="html"/>
						<key name="java"/>
						<key name="makefile"/>
						<key name="nix"/>
						<key name="perl"/>
						<key name="php"/>
						<key name="pnuts"/>
						<key name="sql"/>
						<key name="web-jsptaglibrary_1_1"/>
						<key name="xml"/>
						<key name="xslt"/>
					</key>
				</key>
			</hierarchicalconfig>
		</plugin>
```
Есть одна идея - проверить JP Software Take Command - там в отличии от CMD как раз есть поддержка полной палитры sRGB что видно в его настройках когда выставляешь цвета.  А в CMD на семёрке цвета произвольно меняются.

**Comment by ctapmex** [comment]
win7 под руками нет. 
 Windows 10 + truemod
![truemod_woVirt](https://user-images.githubusercontent.com/1277115/114736962-00286280-9d60-11eb-8131-e900b427f224.PNG)
 Windows 10 + truemod +  Use Virtual Terminal for rendering  
![truemod_wVirt](https://user-images.githubusercontent.com/1277115/114736978-04548000-9d60-11eb-8f05-fef8a205fbf3.PNG)

Но я не понимаю, что не устраивает. Сидеть в truemod без Use Virtual Terminal for rendering  или ConEmu какой смысл ? доступны 16 цветов, аппроксимация идет до ближайшего цвета. Да, ранее она была другая. Сейчас поменяли выровняв поведение при задании цвета через ручной ввод или из палитры. Вполне себе обосновано.
со стороны Colorer тут ничего не сделать. да и ни к чему

**Comment by VictorVG** [comment]
Причина не в "поменяли" а том, что апроксимирующие цвета приводят к смещению в цветовой палитре. Я специально посмотрел - выбранная сейчас апроксимация приводит к выбору неправильных цветовых координат в RGB/sRGB палитре т..к. результат "корректируется" фильтром ОС, а вот к нему у оптики вопросов не менее чем к нерадивому студенту - вывели в 1909 эталонную цветовую плашку на экран - цвета улетели, хотя до эксперимента систему "Сканер - ОС - Экран - Печать" оптики откалибровали по цвету с помощью аппаратного цветокалибратора, но результат был "далёк от ожидаемого" - красный 0xFF0000 был интерпретирован консолью как маджента - 0хFF00FF, а "контора" сказала "Не понимаем суть проблемы - вы же видите цветное изображение!?" - всё правильно,  полетели цвета это мелочи, и так сойдёт!

**Comment by VictorVG** [comment]
Это конечно правильно :) - цвет RGB 0x5555DD заменяем на RGB 0x0a0078 ибо "голубой ~= синий" == "светло-серый". Так работает "лучшая консоль с идеальными цветами" от Майкрософт и ... b5765+.... Мне наверное к окулисту .....
