### ISSUE TITLE
FarColrer 1.3.25 - nmake exit code 0x2 при сборке в VC++ 15.9.35 (VC++2017)

### ISSUE THREAD

**Issue by VictorVG** [colorer/FarColorer#50]
Затея тут пересборку - Git e7e94b44e951 собрался, ну я и переписал тулкит на один общий скрипт build.cmd ([build.cmd.zip](https://github.com/colorer/FarColorer/files/6415578/build.cmd.zip)) дабы меньше ошибок возникало он сам и исходники возьмёет, и Ant, а тут Git deecb78790c свалился и распишитесь - куча варнингов, а в итоге нмаке выводит код 2 - бинарника нет. Лог собрал, но он здоровенный ~ 150,5 КБ текста. 

[vc2017_log.txt](https://github.com/colorer/FarColorer/files/6415567/vc2017_log.txt)

Переключил скрипт на VC2019 - в первом варианте по дефолту стояла 2017 т.к. и ХР поддерживает, и сам компилятор быстрее - собрала, хотя более тормозной студии после 16.7.7 я не видел :( - скорость компиляции по сравнению с 2019 v16.7.7 снизили почти втрое - Process Hacker  (его CustomBuildTools выводит время затраченное на сборку что удобно для оценки) берём один и тот же коммит - на VC++2019 v16..7.7 - 1 мин 37 сек - 1мин 43 сек, а начиная с VC++2019 v16.8.0 не быстрее 3 мин 30 сек - "_Мы значительно увеличили производительность компилятора!_" :) И это не на самой слабой машине:

CPU:           Intel Xeon E5-2667
BIOS:          4.6.5, 10/29/2019, AMI, UEFI
Motherboard:   QUIDA X79-P3
Chipset:       Intel C602J (Patsburg)
Memory:        16 GBytes REG ECC DDR3-1866, Quad Chanel, 12-12-12-32 Cr=1 tRfc=98
               - 4096 MB - Samsung M393B5170GB0-CK0
               - 4096 MB - Samsung M393B5170GB0-CK0
               - 4096 MB - Samsung M393B5170GB0-CK0
               - 4096 MB - Samsung M393B5170GB0-CK0
Graphics:      MSI GTX 1660 Ventus XS OC, TU116, 6 GB GDDR5
Drive:         ST3160815AS, 160 GB, SATA 3 Gb
Drive:         TOSHIBA HDWD120, 2.0 TB, SATA 6 Gb
Drive:         TOSHIBA HDWD130, 3.0 TB, SATA 6 Gb
Drive:         WDC WD2500AAJS-00B4A0, 250 GB, SATA 3 Gb
Drive:         ST1000LM025 HN-M101ABB, 1.0 TB, USB 3.0
Drive:         ST2000LM007-1R8174, 2.0 TB, USB 3.0
Drive:         TOSHIBA MQ04UBD200, 2.0 TB, USB 3.0
Drive:         WDC WD20NMVW-11AV3S2, 2.0 TB, USB 3.0
Drive:         PIONEER DVD-RW DVR-221L
Sound:         RealTek Semiconductor ALC892 - HD Audio
Network:       RealTek Semiconductor RTL8111F
Power Suplay:  AeroCool AERO BRONZE 850M 850W
KBD + Mouse:   Lenovo L500-K
Display:       Philips Brilliance 235BL

(БП на той неделе менял - в Чифтеке взорвался чип выпрямителя в дежурке (+5VSB) - блок валяется на ремонт как руки дойдут - БП на 750 Вт как никак пригодится:))

**Comment by ctapmex** [comment]
проверь, должно работать

**Comment by VictorVG** [comment]
Да, собралось - пришлось подождать т.к. вторая машина медленее - там i7-2600 (основная по производительности равна рабочей станции DEL Precesion 5800 с Xeon E5-2667/128 Gb RAM/QUADRO 5200 :)) и даже парасслеьно собирая Colorer + Far + Process Hacker шустрая:

Windows: Windows NT 6.1.7601.0
WindowsSDK: 19041 (16.9.31004.209)
VisualStudio: VisualStudio/16.9.4+31205.134

Building... 3.0.8553.4026 (859a4c4) [master]

[00:00] Building ProcessHacker (x32)...
[01:14] Building ProcessHacker (x64)...
[02:33] Building Plugins (x32)...
[03:14] Building Plugins (x64)...
[03:53] Building build-bin.zip... 6Mb
[03:54] Building build-setup.exe... 9Mb
[04:02] Building build-pdb.zip... 44Mb
[04:09] Building build-sdk.zip... 9Mb
[04:10] Building release checksums...

Build Time: 4 minute(s), 10 second(s)

**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.9.4
** Copyright (c) 2021 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x86'

Building ExtraPlugins        [SUCCESS]
Clean deleted plug-ins        [SUCCESS]
Copying signed KPH driver   [SUCCESS]
Create PluginsData dir   [SUCCESS]
Copy Terminator driver   [SUCCESS]
Building Setup    [SUCCESS]
Building Process Hacker SDK      [SUCCESS]
Building ProcessHacker Zip      [SUCCESS]
Building source tarball      [SUCCESS]
Generating checksums        [SUCCESS]

 Ну а с тулкитом я косметику в версии 1.4.1 навожу - файл version в каждом выходном гнаборе не задуман - это нам для удобства ориентации какой коммит был использован.

**Comment by VictorVG** [comment]
[**FarColorer build toolkit v1.4.1**](https://github.com/VictorVG/Source/releases/tag/FCTK-1410) - готово. Сделал всё, чтобы нам было удобно - ант загружается автоматом, выбор студии, JDK, по завершении в ./build лежит файл version с хэшами использованных коммитов. Мусор от сборки подчищается налету.
