### ISSUE TITLE
Patch - завершим перевод английской справки, вылов опечаток в русской и их рефакторинг для читаемости.

### ISSUE THREAD

**Issue by VictorVG** [colorer/FarColorer#52]
Patch - завершим перевод английской справки, вылов опечаток в русской и их рефакторинг для читаемости.

Посмотрел - не все опечатки в **#51** выловили, да и в английской справке кусок был на русском - значит и её допереведём. Правда перевод стоит перепроверить - вдруг я где-то ошибся? 

Дифф - ColorerHlf.diff большой (~ 63k / 959 строк), потому положил в Zip вместе с исправленными файлами: [**colorerhlf.zip**](https://github.com/colorer/FarColorer/files/6447622/colorerhlf.zip) .

**P.S.**

_С Днём Победы!_

**Comment by VictorVG** [comment]
Немного косметики [ColorerHlf.zip](https://github.com/colorer/FarColorer/files/6448061/ColorerHlf.zip)

**Comment by ctapmex** [comment]
спасибо. русский применю с небольшими изменениями, Над английским файлом надо будет поработать еще

**Comment by VictorVG** [comment]
Годится. С английским наверняка нужна доработка т.к. я технарь и его стоит "олитературить".

**Comment by VictorVG** [comment]
https://github.com/colorer/FarColorer/commit/11a06da443ae0ace93abb5830c12b06353c4a79e стоит и в ветку v1.3.x смержить а то там у нас пока старый вариант справки...
