### ISSUE TITLE
Случайные во времени падения FarColorer v1.3.29 (включительно) при сохранении некоторых HTML и логов Git.

### ISSUE THREAD

**Issue by VictorVG** [colorer/FarColorer#59]
В случайный момент времени падаем при сохранении файла или на длинных строках HTML, или на логах гит выводимых командой

git log > log.txt

с кодом ошибки ОС 0x40000015 {Неустранимая ошибка приложения}, причём момент падения всегда случайный.
последний по времени краш-лог: [**bug_report.txt**](https://github.com/colorer/FarColorer/files/6709062/bug_report.txt) и полный набор - bug_report.txt, far.mdmp, Far.pdb (от моей сборки b5833 на которой упали - исходники ищутся по пути I:\dev\Far3\1\fardev\ куда склонирован мастер из репо фар-а ), Far.exe.19060.dmp, far_full.mdmp, readme.txt - [**Far.2021.06.24_11.49.28.685_19060.7z**](https://www.upload.ee/files/13260792/Far.2021.06.24_11.49.28.685_19060.7z.html)

Архив 7-Zip 21.02 Alpha, LZMA2, SOLID .

Явление воспроизводится на версиях колорера от 1.3.26 по 1.3.29 включительно, причину пока не обнаружил.

**Comment by ctapmex** [comment]
какая длина строки? примерно хотя бы.

**Comment by VictorVG** [comment]
По разному попадается, но обычно от 200 символов и набитые скриптами страницы по 150 кб и более, например стоит посмотреть страницы с Яндекс.Дзен - у них там CSS-и на несколько тысяч строк, а сам файл сохраняемый симанкой достигает 700 - 900 Кб, и подало если в строке несколько тэгов, например если браузеру в исходнике попался скриптивместо его тела осталась конструкция типа <script ...></script>. Я сохраню образец такой страницы при падении т.к. правлю заинтересовавшие меня страницы убирая из них скрипты и прочий мусор, а после компилю в CHM.

**Comment by VictorVG** [comment]
Ну, сегодня на диффе упали - в Process Hacker нет части кода и тот падает, потребовался дифф чтобы поглядеть можно ли поправить - созда, попытался сохранить как ASCII/Text - в момент сохранения файла упали с дампами и логом [**Far.2021.08.13_18.47.02.822_5076.7z**](https://www.upload.ee/files/13391552/Far.2021.08.13_18.47.02.822_5076.7z.html). В архиве дампы, far.pdb  от упавшей копии (путь к сорцам I:\dev\Far3\1\FarDev\), сам дифф на котором в этот раз упали.

Как гипотеза - т.к. падаем обычно на сохранённых в файл логах git pull имеющих вид типа:
```
Git: 12.08.2021 10:08:23,93
 
Updating f2007892b..6f249b553
Fast-forward
 far/FarCze.hlf.m4    |    3 -
 far/FarEng.hlf.m4    |    3 -
 far/FarGer.hlf.m4    |    3 -
 far/FarHun.hlf.m4    |    3 -
 far/FarPol.hlf.m4    |    3 -
 far/FarRus.hlf.m4    |    3 -
 far/FarSky.hlf.m4    |    3 -
 far/FarUkr.hlf.m4    |    4 -
 far/PluginA.cpp      |    2 +-
 far/changelog        |    5 +
 far/dialog.hpp       |    3 +-
 far/farlang.templ.m4 |    6 +-
 far/macro.cpp        | 2486 +++++++++++++++++++++++++-------------------------
 far/macro.hpp        |    2 +-
 far/manager.cpp      |   35 +-
 far/manager.hpp      |    1 -
 far/plugapi.cpp      |    5 +-
 far/plugins.cpp      |   16 +-
 far/vbuild.m4        |    2 +-
 far/viewer.cpp       |    2 +-
 20 files changed, 1271 insertions(+), 1319 deletions(-)
 
b5875 Git-6f249b553 
```
то, может его строка прогресса выводимая знаками плюс/минус как-то сбивает колорер? На обычнх текстах не падаем, а на логах и вот на диффе упали, а общее - цепочки "арифметики"...

**Comment by VictorVG** [comment]
Возможно, что верятную причину я у себя нашёл и устранил - случайно дублировались два экземпляра плагина _Word Completion_  в подкаталогах EditCompl и ECompl, ну и ещё была куча накопившегося мусора . Пришлось основательно его почисть по сети. Сейчас попровал поправить лог Git - убрал дублирующиеся строки, и при сохранении не упали. Понаблюдаю - если причиной было дублирование плагинов - ну отлично, заодно и мусор повычистил, а это всегда полезно...

**Comment by VictorVG** [comment]
Да, это и было причиной падений - пока их нет.
