### ISSUE TITLE
Перестали подцепляться схемы из hrc/auto

### ISSUE THREAD

**Issue by viccpp** [colorer/FarColorer#64]
... после обновления на Far 3.0.5959

**Comment by joric** [comment]
@viccpp я обнаружил проблему с именами - обработка файлов hrc зависит от имени файлов по алфавиту (файлы выше не грузят файлы ниже), но это не специфично для 5959. 5952 ведет себя точно так же. Сам колорер-плагин ведь не обновлялся с декабря 2021. https://forum.farmanager.com/viewtopic.php?p=170695#p170695

**Comment by ctapmex** [comment]
@viccpp  актуально?

@joric  В библиотеке есть кросс-референс. Но для этого при загрузке схемы он точно должен знать, что тип, на который, ссылается , точно есть. А это решают файлы типа proto.hrc.
т.е. в папку auto лучше положить аналог proto.hrc, который будет ссылаться на другие папки.

**Comment by viccpp** [comment]
Ну как сказать... Путь без объявления войны поменялся с `hrc/auto` на `auto/types`. Если переписать конфиги и переместить файлы, то всё заработает. Могли бы, если не скрипт для миграции, то хотя бы предупреждение с подробными инструкциями предоставить вместе с обновлением.

**Comment by ctapmex** [comment]
исправимся

**Comment by viccpp** [comment]
Обновился на 3.0.6300. Расцветка пропала вообще

**Comment by viccpp** [comment]
Виновный найден - это ArcLite, перепаковывающий `common.zip` в нечитаемый формат. Если `common.zip` не трогать или явно выбирать метод `Deflate`, то всё работает.

**Comment by ctapmex** [comment]
да, есть такая пакость. в #86  обсудили
