### ISSUE TITLE
`def:StringEdge` overrides `def:Insertion` in block

### ISSUE THREAD

**Issue by Kojoley** [colorer/FarColorer#68]
For some reason when I define `region10="pyStringEdge"` it toggles of embedded block background, (Python updated scheme from https://github.com/colorer/Colorer-schemes/pull/137)
```xml
  <scheme name="ReplacementField">
    <block start="/\{/" end="/$|\}/"
       scheme="FExpression" region="def:Insertion"
       region00="pyStringEdge" region10="pyStringEdge" />
  </scheme>
```
![image](https://user-images.githubusercontent.com/2743474/190245343-2fc7d94e-9158-4596-afa4-7790c0feca63.png)
```xml
  <scheme name="ReplacementField">
    <block start="/\{/" end="/$|\}/"
       scheme="FExpression" region="def:Insertion"
       region00="pyStringEdge"                         />
  </scheme>
```
![image](https://user-images.githubusercontent.com/2743474/190245469-ae8a6542-a53a-4acb-ae87-cabcb0d2b579.png)

**Comment by ctapmex** [comment]
fixed in 9582f77aa6f79e8dd6a742b5900a435ce1d40992
FarColorer 1.4.28
