### ISSUE TITLE
Windows 11 strange initial color

### ISSUE THREAD

**Issue by hordi** [colorer/FarColorer#70]
This happened after update from Windows 10 to Windows 11.
When I start FAR I see light blue color. 
If enter console mode (CTRL-O) and run any fake command (like "djsdjsjd") and press ENTER - original FAR color will be restored.
The icon in task bar is also not original.

Here screenshot for Far Manager v3.0 build 6056 x64 (2022-11-25) before and after "CTRL-O + "djsdjsjd" run":

![image](https://user-images.githubusercontent.com/45203053/204065471-32979dc9-409b-448d-a57e-52d2df5ef4dd.png)

![image](https://user-images.githubusercontent.com/45203053/204065605-05838bde-9ce2-481d-bc78-6b5fcc660e98.png)

**Comment by ctapmex** [comment]
The FarColorer has nothing to do with it.
Look https://forum.farmanager.com/viewtopic.php?t=11350
