### ISSUE TITLE
Hang when loading large .js file

### ISSUE THREAD

**Issue by phantasm** [colorer/FarColorer#72]
When trying to open this file for editing, Far hangs on "Far Colorer - Reloading schema library" window.
[extension.js.zip](https://github.com/colorer/FarColorer/files/10608708/extension.js.zip)
Far v.3.0.6060.0 x64 (public release)
Far v.3.0.6099.0 x64 (nightly)

**Comment by yegor-mialyk** [comment]
I think the problem is that this JS file has one long line.  Also it is better to report this problem in the plugin's repo: https://github.com/colorer/FarColorer

**Comment by phantasm** [comment]
@yegor-mialyk I thought we're already in this repo :)

**Comment by yegor-mialyk** [comment]
oops :D

**Comment by AVBL** [comment]
(Перенаправлено с https://github.com/FarGroup/FarManager/issues/637 )
Среди файлов Steam есть, например, такие файлы:
![image](https://user-images.githubusercontent.com/49921898/221057231-312372ff-ee6f-4824-9e96-6836ff5e50e2.png)
При попытке открыть один из этих файлов на редактирование Far задумывается на долгое время (4-5 минут):
![image](https://user-images.githubusercontent.com/49921898/221057621-6220b577-2500-4366-b86d-431c589b5ec1.png)
при этом очень сильно нагружая процессор:
![image](https://user-images.githubusercontent.com/49921898/221057653-f8ac54d6-5463-4113-90a5-1678ec8a78be.png)
и в результате не открывая файл. Для удобства присоединяю один из этих файлов стима.
[sp.js.zip](https://github.com/FarGroup/FarManager/files/10819427/sp.js.zip)

**Comment by ctapmex** [comment]
fixed in FarColorer v1.4.18
