### ISSUE TITLE
Crash with `Editor.ShowWhiteSpace=true|other` after `2e9050b`

### ISSUE THREAD

**Issue by bitraid** [colorer/FarColorer#81]
FarColorer crashes after 2e9050bd84b668ae64628a459e51da3353cccab7, when the Editor is set to show white space.
The reason is that `egs` is null in:
https://github.com/colorer/FarColorer/blob/4a78175623bb9c6840003c6f949024def6b42a8b/src/FarEditor.cpp#L591
A simple check seems to fix the problem.

**Comment by ctapmex** [comment]
fixed, check https://github.com/colorer/FarColorer/releases/tag/v1.4.22

**Comment by bitraid** [comment]
Awesome :+1:
