### ISSUE TITLE
Syntax highlighting errors in Registry and Bash files

### ISSUE THREAD

**Issue by rohitab** [colorer/FarColorer#82]
Registry, Bash and possibly other files, are displaying syntax highlighting errors in FarColorer version `1.4.22`. In the previous version, `1.4.21`, these files were displayed without errors. However, in that version, there was an issue with files without extensions. See #80 for more info. The last version where everything is working correctly is `1.4.19`. Attached are [`Sample Files`](https://github.com/colorer/FarColorer/files/14317162/Sample-Files.zip) I used for testing.

### Registry
![registry-syntax-errors](https://github.com/colorer/FarColorer/assets/800999/cdd93d2c-dea8-4c99-a1dd-eab2ccfda830)

### Bash
![bash-syntax-errors](https://github.com/colorer/FarColorer/assets/800999/cdc7bcbe-03f8-4022-a3a7-90d35a167aeb)

### Versions

| Version | Registry | Bash | No Extension |
|--------|--------|--------|--------|
| 1.4.19 | ✅ | ✅ | ✅ |
| 1.4.20 | ✅ | ✅ | ❌ |
| 1.4.21 | ✅ | ✅ | ❌ |
| 1.4.22 | ❌ | ❌ | ✅ | 

Tested with Far Manager, version `3.0.6274.0 x64`

### Attached Files

- [`Sample-Files.zip`](https://github.com/colorer/FarColorer/files/14317162/Sample-Files.zip)

**Comment by nightroman** [comment]
Also, PowerShell files are colored incorrectly in 1.4.22 . 16.02.2024.
I did not check anything else, I returned to the previous Far download.

**Comment by ctapmex** [comment]
sorry -( revert changes

**Comment by rohitab** [comment]
No problem and thank you! Everything looks good in `1.4.0.23`
