### ISSUE TITLE
FarColorer crashes in version FM 6300 after modifying proto.hrc in common.zip

### ISSUE THREAD

**Issue by eperovgit** [colorer/FarColorer#86]
Hi,
With new FX version 6300 I updated the proto.hrc in common.zip to add more extension for SQL
        <filename>/\.sql$/i</filename>
to
        <filename>/\.(sql|pkg|prc|fnc|trg|typ|vw|grn)$/i</filename>.
Steps to change **proto.hrc** in zip:
Click Enter on the zip file **common.zip**
Edit **proto.hrc**
Esc - Save - Yes - Add files to archive - OK
Save F2 - FM recreates ZIP

After that opening any file with F4 shows a red error window.

The same modification is working in FM 6226.
I believe, there is some problem in ZIP -ing.

I noticed when the content of the proto.hrc is not changed like: edit proto.hrc as described above delete **sql** string and then type **sql** again, so actually there is no change just to force rezipping common.zip.
After saving common.zip has different size
16-Mar-24  12:09         1,611,551 common_org.zip
09-Apr-24  10:01         1,611,214 common_new.zip
After that the error with editing files occurs.

I tried to create common.zip by uncompressing it and then compress using the zip command:
zip -r common.zip *
the problem still persists.

The common.zip modified as above from FM 6226, successfully works with FN 6300.

What command is being used to create **common.zip**?

Thanks

**Comment by ctapmex** [comment]
The problem is caused by changes in the arclite plugin. He chooses the wrong compression algorithm. You need to use 'deflate'. I'll try to see what exactly is wrong with the arclite plugin.

**Comment by ctapmex** [comment]
after https://github.com/FarGroup/FarManager/issues/781 acrlite uses the default LZMA algorithm when updating the archive.  And FarColorer only works with deflate.

**Comment by eperovgit** [comment]
Thank you very much.
Creating common.zip with the "Deflate" option fixes the isue.
